### ISSUE TITLE
Validation of input? 

### ISSUE THREAD

**Issue by prashantbarca** [lost-plus-found/ACOE-Result-Command-Line#1]
What do you do when the password is incorrect? I don't see any check for that? 
`
Hi, this is a one time installation

Register Number: 2011103043
Password: 
sed: 1: "auresult": command a expects \ followed by text
sed: 1: "auresult": command a expects \ followed by text
Installing...
install -m775 -d /usr/local/bin
`

**Comment by prabhakaran9397** [comment]
Even I thought of handing but, curl returns with a response login failed.

Oh, I didn't use curl during install, I'll note down that.

Try
auresult -n
(For incorrect username or password)
It'll return login failed

**note: acoe site is down from morning :(
Check if its opening, if yes it'll work

**Comment by prabhakaran9397** [comment]
Hi,

I've updated install file with validation of inputs and server timeout check. Also handled server timeout for auresult command.

(ACOE website is still down :-1:  )

**Comment by prabhakaran9397** [comment]
Now the server is up!
Try it now.
:)
